apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: first-operator
  template:
    metadata:
      labels:
        name: first-operator
    spec:
      serviceAccountName: first-operator
      containers:
        - name: first-operator
          # Replace this with the built image name
          image: docker.io/cfgarden/podset-operator
          command:
          - first-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "first-operator"
